# Generated by Django 4.1.3 on 2022-11-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='movieapp', upload_to='galary'),
            preserve_default=False,
        ),
    ]
